### ISSUE TITLE
Change the "SHOW" text to "HIDE" depending on state

### ISSUE THREAD

**Issue by WychWitch** [itinerare/Mundialis#29]
**Is your feature request related to a problem? Please describe.**
The SHOW button for the field or section is a little confusing when it's already showing everything. 

**Describe the solution you'd like**
I would prefer if the text switched to HIDE when displaying everything, and SHOW when the element is hidden.

**Describe alternatives you've considered**
I found [this](https://css-tricks.com/swapping-out-text-five-different-ways/) post showing potential solutions, one of them being pure CSS (though, a little hacky).

**Additional context**
![image](https://user-images.githubusercontent.com/1291820/143674706-add37048-2b35-4fec-861b-1680564cdbe0.png)
![image](https://user-images.githubusercontent.com/1291820/143674709-4430715b-4d7a-4df3-95b3-e64832120498.png)

**Comment by itinerare** [comment]
Hmm. I'll look into it!
