### ISSUE TITLE
Mothcat, Faeloras, and other sites are listed in config/backup.php

### ISSUE THREAD

**Issue by WychWitch** [itinerare/Mundialis#33]
**Describe the bug**
This is less of a bug, and more just noticing info that probably shouldn't be there; it's just names in the backup.php but it could be more?

**To Reproduce**
1. Go to config/backup.php
2. open it
**Expected behavior**
For those other sites to not be there, probably?

**Screenshots**
![image](https://user-images.githubusercontent.com/1291820/144737087-2f418214-f670-42a3-afa3-08fb8e150399.png)

**Comment by itinerare** [comment]
SIGHS
I'll fix it, thank you for letting me know
