### ISSUE TITLE
Reorder images/custom image order

### ISSUE THREAD

**Issue by baratomott** [itinerare/Mundialis#489]
**Is your feature request related to a problem? Please describe.**
Not being able to rearrange images and/or having specific images at the top of the gallery causes a little difficulty for referencing purposes, especially when there are many images for a page.

**Describe the solution you'd like**
The ability to reorder images and/ or pin specific images to the top of the page's gallery.

**Describe alternatives you've considered**
Uploading images in the order you want them to appear in or more liberal use of the "is valid/invalid" image settings.

**Comment by itinerare** [comment]
Yeah, I can figure something out for that!
