### ISSUE TITLE
Removing dates that an event had previously used causes "$date is undefined" 500 error

### ISSUE THREAD

**Issue by WychWitch** [itinerare/Mundialis#55]
**Describe the bug**
If you create an event, give it a date, and then later delete that date the event will now have no date to refer to, resulting in a `$date is undefined ` error.

**To Reproduce**
1. Create a division of time, and set it to be used as a date
2. Create an event
3. Set the event to use one the previously created division of time
4. Delete division of time
5. Return to event

**Expected behavior**
Either for the date to not allow me to delete it until the event was edited, or for the event to simply remove any invalid dates from its page completely.

**Screenshots**
![image](https://user-images.githubusercontent.com/1291820/149979519-19691de7-1591-479c-b295-adf71d02fcca.png)

**Additional context**
Text version of above 
<details>
<summary>text version of above</summary>

```php
//...
            $fields[str_replace(' ', '_', strtolower($division->name))] = [
                'label' => $division->name,
                'type' => 'number',
                'rules' => null,
                'choices' => null,
                'value' => null,
                'help' => null
            ];
        }
        return $fields;
    }

 

    /**
     * Return a formatted datestring using date-enabled divisions.
     *
     * @param  array    $data
     * @return string
     */

    public function formatTimeDate($data)
    {
        // Cycle through date-enabled divisions and add a formatted string to the array
        foreach($this->dateEnabled()->orderBy('sort')->get() as $division) {
            if(isset($data[str_replace(' ', '_', strtolower($division->name))]))
                $date[] = $division->displayName.' '.$data[str_replace(' ', '_', strtolower($division->name))];
        }
        return implode(', ', $date);
    }
}
```
</details>

**Comment by itinerare** [comment]
I'll look into it!
