### ISSUE TITLE
Rogue space, Headers already sent error

### ISSUE THREAD

**Issue by JuniJwi** [itinerare/Mundialis#70]
**Describe the bug**
The _/routes/fortify.php_ file has a single space at the very beginning before the `<?php` tag which causes the "Cannot modify header information - headers already sent" error. For some reason, this error didn't occur on local, but effected live on dreamhost.

Just need to clean up/remove the space before the <?php> tag!

**Comment by itinerare** [comment]
Bizarre! Thanks for letting me know!
